project:
  type: website

website:
  reader-mode: true
  title: "CSSS 508"
  navbar:
    left:
      - syllabus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

