project:
  type: website
  output-dir: docs
  # render:
  #   - "*.qmd"
  #   - "!Homework/CSSS508_HW1_*.qmd"
  #   - "!notes/*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    grid: 
      sidebar-width: 300px
      body-width: 1000px
    fontsize: 1.1rem

website:
  reader-mode: true
  title: "CSSS 508"
  navbar:
    left:
      - syllabus.qmd
      - file: Lectures/lectures.qmd
        text: "Lectures"
      - file: Homework/homework.qmd
        text: "Homework"
  sidebar: 
    - title: "Lectures"
      style: "docked"
      contents: 
        - Lectures/lectures.qmd
        - file: Lectures/lec1_intro.qmd
          text: "Lecture 1: Getting started"
        - file: Lectures/lec2_data_manip.qmd
          text: "Lecture 2: Data manipulation with base R"
        - file: Lectures/lec3_data_manip_tidyverse.qmd
          text: "Lecture 3: Data manipulation with tidyverse"

    - title: "Homework"
      contents: 
        - Homework/homework.qmd
        - file: Homework/homework1.qmd
          text: "Homework 1"
        - file: Homework/homework2.qmd
          text: "Homework 2"

