project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  title: "CSSS 508"
  navbar:
    left:
      - syllabus.qmd
      - file: Lectures/lectures.qmd
        text: "Lectures"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

