---
title: "Homework 3"
highlight-style: a11y-dark
---

### Instructions

Create a new Quarto document (.qmd file) for this new homework; always use a new Quarto document for each homework.

In your Homework 3 Quarto document, continue to explore the `gapminder` dataset from the **gapminder** package, following the instructions below. Your document should be pleasant for a peer to look at, with some organization using section headings. Use chunk options to control which code and raw output you show in the html file when you render your Quarto document. When you've completed the assignment, upload to Canvas both the `.qmd` file and the `.html` file it generates when you render the `.qmd` file.

Detailed instructions for HW3:

  - Organize your report in a few sections with appropriately named and Markdown-formatted section headings.
  
  - Use an Introduction or Data section at the start of the report to summarize in sentences what the dataset is, where it comes from, what variables it includes and what they mean. Try to add one piece of information to what you wrote in your HW2.
  
  - Make a table of some subset of rows and columns of the dataset (different from the one you made in HW2) two different ways, one using base R and one using **tidyverse**. In other words, you should have two chunks of code making the same table, and both chunks of code and both tables should show up in your rendered html file.
  
  - Then use Markdown text (not just code comments) to summarize your approach to writing these two different chunks of code. Use code-style text formatting `like this` to make code references in your text look like code, just as in the lecture notes (e.g. when I write about `mutate()` and `gapminder`).
  
  - Compute the number of Asian countries in the dataset two different ways, one using base R and one using **tidyverse**. Use chunk options to make sure your code for both approaches is displayed in your rendered html file, not hidden, and insert one of the two results (they should be the same as each other) into a text sentence using inline code.
  
  - Using either base R or **tidyverse**, compute the number of observations with at least 29 million people in 1952, and report your answer using inline code. Then pose a similar problem for the other student to try, and report the code and answer in your html file with a brief explanation of your solution!
  
  - State one thing you didn't do to your satisfaction in HW2 and how you have improved upon it in HW3. For instance, maybe you corrected some aspect of a table or of the Quarto html formatting in HW3 that wasn't working in your HW2 submission.
  
  - Most of all, have some fun practicing what we did in class and any other R/RStudio/Quarto features you might be discovering!

